# Generated by Django 4.2.25 on 2025-11-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload your company logo (recommended size: 200x60px)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='website_url',
            field=models.URLField(blank=True, help_text='Your company website URL', null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.TextField(default='123 Business Street, City, Country', help_text='Company address'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='company_name',
            field=models.CharField(default='TechSolutions Pro', help_text='Your company name (shown in header and footer)', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(default='info@techsolutionspro.com', help_text='Contact email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook page URL'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub profile/company URL'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn company page URL'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(default='+1 (555) 123-4567', help_text='Contact phone number', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='tagline',
            field=models.CharField(default='Transforming Ideas into Digital Solutions', help_text='Company tagline or slogan', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter profile URL'),
        ),
    ]
