# Generated by Django 4.2.20 on 2025-11-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_sitesetting_logo_sitesetting_website_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='notification_email',
            field=models.EmailField(blank=True, help_text='Email address where project requests will be sent', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='smtp_host',
            field=models.CharField(blank=True, help_text='SMTP server host (e.g., smtp.gmail.com)', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='SMTP password or app password', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='smtp_port',
            field=models.IntegerField(default=587, help_text='SMTP server port (587 for TLS, 465 for SSL)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='smtp_username',
            field=models.EmailField(blank=True, help_text='SMTP username (usually your email address)', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='use_tls',
            field=models.BooleanField(default=True, help_text='Use TLS encryption (recommended)'),
        ),
    ]
