# Generated by Django 4.2.20 on 2025-11-08 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_sitesetting_notification_email_sitesetting_smtp_host_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title (e.g., Senior Python Developer)', max_length=200)),
                ('department', models.CharField(blank=True, help_text='Department (e.g., Software Development)', max_length=200)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote')], default='full_time', max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level (0-2 years)'), ('mid', 'Mid Level (2-5 years)'), ('senior', 'Senior Level (5+ years)')], default='mid', max_length=20)),
                ('location', models.CharField(help_text='Job location (e.g., Remote, New York, etc.)', max_length=200)),
                ('salary_range', models.CharField(blank=True, help_text='Salary range (e.g., $50,000 - $80,000)', max_length=100)),
                ('short_description', models.TextField(help_text='Brief job description (shown in listing)')),
                ('full_description', models.TextField(help_text='Complete job description with all details')),
                ('requirements', models.TextField(help_text='Required skills, qualifications, and experience')),
                ('responsibilities', models.TextField(help_text='Job responsibilities and duties')),
                ('preferred_qualifications', models.TextField(blank=True, help_text='Preferred but not required qualifications')),
                ('technologies', models.CharField(blank=True, help_text='Technologies/tools (e.g., Python, Django, React, PostgreSQL)', max_length=500)),
                ('benefits', models.TextField(blank=True, help_text='Benefits and perks offered')),
                ('application_deadline', models.DateField(blank=True, help_text='Application deadline (optional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show this job on website')),
                ('featured', models.BooleanField(default=False, help_text='Feature this job on homepage')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-featured', '-order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('current_location', models.CharField(blank=True, max_length=200)),
                ('current_position', models.CharField(blank=True, help_text='Current job title', max_length=200)),
                ('current_company', models.CharField(blank=True, max_length=200)),
                ('years_of_experience', models.IntegerField(default=0, help_text='Years of relevant experience')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('portfolio_url', models.URLField(blank=True, help_text='Portfolio or GitHub URL')),
                ('resume', models.FileField(help_text='Upload your resume (PDF, DOC, DOCX)', upload_to='resumes/%Y/%m/')),
                ('cover_letter', models.TextField(blank=True, help_text='Cover letter or additional notes')),
                ('availability', models.CharField(blank=True, help_text='When can you start?', max_length=200)),
                ('expected_salary', models.CharField(blank=True, help_text='Expected salary range', max_length=100)),
                ('notice_period', models.CharField(blank=True, help_text='Notice period (e.g., 2 weeks, 1 month)', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview Scheduled'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes (not visible to applicant)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='website.job')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
